version: '2'

services:

  quexf:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./location-of-forms:/forms
    environment:
      QUEXF_DB_PASSWORD: password
      QUEXF_ADMIN_PASSWORD: password

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"